---
 - hosts: all
   gather_facts: false
   become: yes
   tasks:
   - yum:
        name: "{{ item }}"
        state: present
     loop:
        - httpd
        - php
        - php-mysql
        - https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
        - mysql-server
     notify:
        - restart httpd
        - restart mysql
    - copy:
         src: /root/index.html
         dest: /var/www/index.html
   handlers:
   - name: restart httpd
     service:
       name: httpd
       enabled: yes
       state: restarted
   - name: restart mysql
     service:
       name: mysqld
       enabled: yes
       state: restarted
