---
 - hosts: web
   gather_facts: false
   become: yes
   tasks:
   - yum:
        name: "{{ item }}"
        state: present
     loop:
        - httpd
        - php
        - php-mysql
        - https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
        - mysql-server
   - copy:
        src: /root/apache/index.html
        dest: /var/www/html/index.html
     notify:
        - restart httpd
        - restart mysql
        - selinux
   handlers:
   - name: restart httpd
     service:
       name: httpd
       enabled: yes
       state: restarted
   - name: restart mysql
     service:
       name: mysqld
       enabled: yes
       state: restarted
   - name: selinux
     seboolean:
       name: httpd_can_network_connect
       state: yes
       persistent: yes

 - hosts: tomcat
   gather_facts: false
   become: yes
   tasks:
   - yum:
        name: "{{ item }}"
        state: present
     loop:
        - tomcat
        - tomcat-webapps 
        - tomcat-admin-webapps
        - tomcat-docs-webapp
        - tomcat-javadoc
   - copy:
        src: /root/apache/tomcat-users.xml
        dest: /usr/share/tomcat/conf/
     notify:
        - restart tomcat

   handlers:
   - name: restart tomcat
     service:
       name: tomcat
       enabled: yes
       state: restarted
