---
 - hosts: all
   gather_facts: yes
   become: yes
   tasks:
   - yum:
        name: '*'
        state: latest
     when: ansible_distribution == "CentOS"
   - apt:
        name: '*'
        state: latest
     when: ansible_os_family == "Debian"
   - yum:
        name: "{{ item }}"
        state: latest
     loop:
        - httpd
     notify: 
        - restart httpd
     when: ansible_distribution == "CentOS"
   - apt:
        name: "{{ item }}"
        state: present
     loop:
        - apache2
     notify:
        - restart apache2
     when: ansible_os_family == "Debian"
   - yum:
        name: "{{ item }}"
        state: latest
     loop:
        - mariadb-server
        - mariadb
     notify: 
        - restart mariadb
     when: ansible_distribution == "CentOS"
   - apt:
        name: "{{ item }}"
        state: present
     loop:
        - mysql-server
     notify:
        - restart mysql
     when: ansible_os_family == "Debian"
   - yum:
        name: "{{ item }}"
        state: latest
     loop:
        - php
        - php-mysql
     notify: 
        - restart httpd
     when: ansible_distribution == "CentOS"
   - apt:
        name: "{{ item }}"
        state: present
     loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-cli
     notify:
        - restart apache2
     when: ansible_os_family == "Debian"
    
   handlers:
   - name: restart apache2
     service:
        name: apache2
        enabled: yes
        state: restarted
   - name: restart mysql
     service:
        name: mysql
        enabled: yes
        state: restarted
   - name: restart httpd
     service:
        name: httpd
        enabled: yes
        state: restarted
     when: ansible_distribution == "CentOS"
   - name: restart mariadb
     service:
        name: mariadb
        enabled: yes
        state: started
     when: ansible_distribution == "CentOS"
