---
 - hosts: all
   become: yes
   tasks:
   - yum: 
        name: wget 
        state: present
 - hosts: all
   become: yes
   tasks:
   - yum: name=httpd state=present
   - yum: name=vim state=present
